# Generated by Django 5.0.7 on 2024-08-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_rolesusuario_firma_digital_firmadigital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_aprobado',
        ),
    ]
