# Generated by Django 5.0.7 on 2024-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rolesusuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
