# Generated by Django 5.0.7 on 2024-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_sede_rolesusuario_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='area',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='rolesusuario',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=10),
        ),
        migrations.AddField(
            model_name='rolesusuario',
            name='sede',
            field=models.CharField(choices=[('EGATUR', 'Egatur'), ('FOCUS', 'Focus')], default='EGATUR', max_length=6),
        ),
        migrations.AlterField(
            model_name='rolesusuario',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('PRACTICANTE', 'Practicante')], default='SISTEMAS', max_length=20),
        ),
    ]
