# Generated by Django 5.0.7 on 2024-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_documento_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesusuario',
            name='es_jefe_area',
            field=models.BooleanField(default=False),
        ),
    ]
