# Generated by Django 5.0.7 on 2024-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rolesusuario_es_jefe_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='visado',
            field=models.BooleanField(default=True),
        ),
    ]
