# Generated by Django 5.0.7 on 2024-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_documento_archivo_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='documentos_firmados/'),
        ),
        migrations.AddField(
            model_name='rolesusuario',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
