# Generated by Django 5.0.7 on 2024-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_documento_archivo_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesusuario',
            name='sede',
            field=models.CharField(choices=[('EGATUR', 'Egatur'), ('FOCUS', 'Focus')], default='EGATUR', max_length=6),
        ),
    ]
