# Generated by Django 5.0.7 on 2024-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_documento_area_documento_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('PRACTICANTE', 'Practicante')], default='SISTEMAS', max_length=20),
        ),
    ]
