# Generated by Django 5.0.7 on 2024-08-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_documento_area_remove_documento_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='asignado_a',
        ),
    ]
