# Generated by Django 5.0.7 on 2024-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_documento_visado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesusuario',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='documento',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='visado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolesusuario',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('COORDINACION_GENERAL_FOCUS', 'Coordinación General Focus'), ('MARKETING_FOCUS', 'Área Marketing Focus'), ('PRACTICANTE', 'Practicante')], default='SISTEMAS', max_length=50),
        ),
    ]
