# Generated by Django 5.0.7 on 2024-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_rolesusuario_prioridad_documento_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='asunto',
            field=models.CharField(blank=True, default='Sin asunto', max_length=100, null=True),
        ),
    ]
